use_frameworks!

target 'DPPageViewController_Example' do
  pod 'DPPageViewController', :path => '../'

  target 'DPPageViewController_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  
  pod 'Masonry', '~> 1.0.2'
  end
end
